name: CD Storybook
on:
  push:
    branches:
      - master
jobs:
  buildStoryBook:
    name: Build StoryBook
    runs-on: ubuntu-latest
    env:
      githubToken2: ${{ secrets.githubToken }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
      - name: Hello world
        run: echo Hello world $FIRST_NAME $middle_name $Last_Name!
      - name: Script build StoryBook
        run: npm run deploy-storybook -- --ci --host-token-env-variable=githubToken2
